Cast occupants from string to float before adding
The DictReader reads all values as strings by default

Thus, when adding the number of occupants during different periods,
the attempt to add strings to an int fails, eg:

  File "/opt/python36/src/oq-engine/openquake/commonlib/readinput.py", line 941, in _add_asset
    tot_occupants += values[occupants]
  File "/opt/python36/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/python36/src/oq-engine/openquake/baselib/node.py", line 768, in context
    raise_(etype, msg, tb)
  File "/opt/python36/src/oq-engine/openquake/baselib/python3compat.py", line 134, in raise_
    raise exc.with_traceback(tb)
  File "/opt/python36/src/oq-engine/openquake/baselib/node.py", line 763, in context
    yield node
  File "/opt/python36/src/oq-engine/openquake/commonlib/readinput.py", line 941, in _add_asset
    tot_occupants += values[occupants]
TypeError: node occupancy: unsupported operand type(s) for +=: 'int' and 'str', line None of /home/cyepes/sara_2018/exposure_models/exposure_model-col.xml