Fixed a crash in the ASCE7 postprocessors
The postprocessors (i.e. compute_rtgm) build a logic tree reduced to a
single source and then recompute the trt_smrs of the sources taken from
the CompositeSourceModel. Since June the trt_smrs are stored in the
`sampling` array of the source, which has a row per logic tree
realization of the *original* (larger) logic tree: assigning the
trt_smrs of the reduced logic tree was raising

    ValueError: could not broadcast input array from shape (3,)
    into shape (24,)

Now the sampling array is resized when necessary, i.e. one sample per
realization of the reduced logic tree. Added a QA test reproducing the
issue with an ambiguous source in a logic tree with extendModel
branches.